GET http://localhost:5075/space-api/stars/1
###

GET http://localhost:5075/space-api/stars
###

POST http://localhost:5075/space-api/stars
Content-Type: application/json

{
    "id": 3,
    "name": "Capella",
    "alias": "Alpha Aurigae",
    "brightness": 0.08,
    "radius": 11.9
}
###

PUT http://localhost:5075/space-api/stars/3
Content-Type: application/json

{
    "id": 3,
    "name": "Capella Aa",
    "alias": "Alpha Aurigae [Aa]",
    "brightness": 0.08,
    "radius": 11.98,
    "planets":[
        {
        "id": 4,
        "name": "MyPlanet",
        "isRocky": true,
        "starId": 0
        }
    ]
}
###

DELETE http://localhost:5075/space-api/stars/3
###

GET http://localhost:5075/space-api/planets
###

GET http://localhost:5075/space-api/planets/0
###

POST http://localhost:5075/space-api/planets
Content-Type: application/json

{
    "id": 2,
    "name": "Neptu",
    "isRocky": false,
    "starId": 0
}
###

PUT http://localhost:5075/space-api/planets/2
Content-Type: application/json

{
    "id": 2,
    "name": "Neptune",
    "isRocky": false,
    "starId": 0
}
###
DELETE http://localhost:5075/space-api/planets/2