//Needs updating - scientifically incorrect info just for testing

GET http://localhost:5075/space-api/stars/1
###

GET http://localhost:5075/space-api/stars
###

POST http://localhost:5075/space-api/stars
Content-Type: application/json

{
    "name": "Sun",
    "alias": "Sol",
    "brightness": 1,
    "radius": 1
}
###

PUT http://localhost:5075/space-api/stars/1
Content-Type: application/json

{
    "name": "Sun",
    "alias": "Sol",
    "brightness": 0.08,
    "radius": 10
}
###

DELETE http://localhost:5075/space-api/stars/1
###

GET http://localhost:5075/space-api/planets
###

GET http://localhost:5075/space-api/planets/1
###

POST http://localhost:5075/space-api/planets
Content-Type: application/json

{
    "name": "Neptu",
    "is_rocky": false,
    "star_id": 1
}
###

PUT http://localhost:5075/space-api/planets/1
Content-Type: application/json

{
    "name": "Neptune",
    "is_rocky": false,
    "star_id": 1
}
###

DELETE http://localhost:5075/space-api/planets/1