GET http://localhost:5075/space-api/stars/1
###
GET http://localhost:5075/space-api/stars
###
PUT http://localhost:5075/space-api/stars/1
Content-Type: application/json

{
    "name": "Sun",
    "alias": "Sol",
    "brightness": -26.75,
    "radius": 1
}

###
PUT http://localhost:5075/space-api/planets/2
Content-Type: application/json

{
    "name": "Saturn",
    "is_rocky": false,
    "star_id": 1
}

###
GET http://localhost:5075/space-api/planets
###
DELETE http://localhost:5075/space-api/planets/1
###
DELETE http://localhost:5075/space-api/stars/1